# Generated by Django 2.0.1 on 2018-01-30 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_user_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='track',
        ),
        migrations.RemoveField(
            model_name='track',
            name='artist_id',
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ManyToManyField(related_name='artists', to='pages.Genre'),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='pages.Artist'),
        ),
    ]
