# Generated by Django 2.0.1 on 2018-02-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20180201_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='genre',
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ManyToManyField(null=True, related_name='artists', to='pages.Genre'),
        ),
    ]
