# Generated by Django 2.0.1 on 2018-02-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20180201_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
