# Generated by Django 2.0.1 on 2018-02-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_user_last_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='preview_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
