# Generated by Django 2.0.1 on 2018-02-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_track_preview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='popularity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
