# Generated by Django 2.0.1 on 2018-02-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_artist_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='popularity',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
