# Generated by Django 2.0.1 on 2018-02-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_track_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='artist_score',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='track_score',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
