# Generated by Django 2.0.1 on 2018-02-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20180214_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='danceability',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='valence',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
