# Generated by Django 2.0.1 on 2018-02-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20180217_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='danceability_score',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='valence_score',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
