# Generated by Django 2.0.1 on 2018-02-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20180218_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unique_score',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
