# Generated by Django 2.0.1 on 2018-02-22 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_user_unique_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='danceability_score',
            new_name='dance_score',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='unique_score',
            new_name='genre_count',
        ),
    ]
